#!/usr/bin/env ruby

##
# zid-128-as-ruby
#
# Generate a Zen identifier (http://www.zidplan.com)
# using 128 bits and implementation as a Ruby script.
#
# Usage:
#
#     zid-128-as-ruby
#
# Example:
#
#     $ zid-128-as-ruby
#     0cb49f132271bf0436a8f0689f87ee9c
#
# ## Tracking
#
#   * Command: zid-128-as-ruby
#   * Version: 4.0.0
#   * Created: 2015-01-25
#   * Updated: 2018-07-06
#   * License: Any of GPL, LGPL, MIT, BSD
#   * Contact: Joel Parker Henderson (http://joelparkerhenderson.com)
##
require 'securerandom'
puts SecureRandom.hex(16)
